[INFO] [launch]: All log files can be found below /home/kol/.ros/log/2025-07-21-11-38-06-851150-elsa-86186
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [86196]
[INFO] [joint_state_publisher-2]: process started with pid [86198]
[INFO] [gzserver-3]: process started with pid [86200]
[INFO] [gzclient-4]: process started with pid [86202]
[INFO] [spawn_entity.py-5]: process started with pid [86204]
[INFO] [ros2-6]: process started with pid [86206]
[INFO] [ros2-7]: process started with pid [86208]
[INFO] [ros2-8]: process started with pid [86211]
[robot_state_publisher-1] [INFO] [1753087088.534056402] [robot_state_publisher]: got segment base_link
[robot_state_publisher-1] [INFO] [1753087088.534224192] [robot_state_publisher]: got segment panda_hand
[robot_state_publisher-1] [INFO] [1753087088.534243028] [robot_state_publisher]: got segment panda_leftfinger
[robot_state_publisher-1] [INFO] [1753087088.534253160] [robot_state_publisher]: got segment panda_link1
[robot_state_publisher-1] [INFO] [1753087088.534263045] [robot_state_publisher]: got segment panda_link2
[robot_state_publisher-1] [INFO] [1753087088.534272176] [robot_state_publisher]: got segment panda_link3
[robot_state_publisher-1] [INFO] [1753087088.534281807] [robot_state_publisher]: got segment panda_link4
[robot_state_publisher-1] [INFO] [1753087088.534292844] [robot_state_publisher]: got segment panda_link5
[robot_state_publisher-1] [INFO] [1753087088.534307795] [robot_state_publisher]: got segment panda_link6
[robot_state_publisher-1] [INFO] [1753087088.534318124] [robot_state_publisher]: got segment panda_link7
[robot_state_publisher-1] [INFO] [1753087088.534328606] [robot_state_publisher]: got segment panda_link8
[robot_state_publisher-1] [INFO] [1753087088.534338863] [robot_state_publisher]: got segment panda_rightfinger
[robot_state_publisher-1] [INFO] [1753087088.534349177] [robot_state_publisher]: got segment world
[joint_state_publisher-2] [INFO] [1753087089.710914106] [joint_state_publisher]: Waiting for robot_description to be published on the robot_description topic...
[spawn_entity.py-5] [INFO] [1753087090.080955040] [spawn_entity]: Spawn Entity started
[spawn_entity.py-5] [INFO] [1753087090.082381311] [spawn_entity]: Loading entity published on topic robot_description
[spawn_entity.py-5] [INFO] [1753087090.086677002] [spawn_entity]: Waiting for entity xml on robot_description
[spawn_entity.py-5] [INFO] [1753087090.105105348] [spawn_entity]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-5] [INFO] [1753087090.105864617] [spawn_entity]: Waiting for service /spawn_entity
[ros2-7] [INFO] [1753087091.659146005] [_ros2cli_86208]: waiting for service /controller_manager/load_controller to become available...
[ros2-8] [INFO] [1753087091.688002893] [_ros2cli_86211]: waiting for service /controller_manager/load_controller to become available...
[gzserver-3] 
[gzserver-3] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[gzserver-3] This error state is being overwritten:
[gzserver-3] 
[gzserver-3]   'Fast CDR exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:118'
[gzserver-3] 
[gzserver-3] with this new error message:
[gzserver-3] 
[gzserver-3]   ''Bad alloc' exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:123'
[gzserver-3] 
[gzserver-3] rcutils_reset_error() should be called after error handling to avoid this.
[gzserver-3] <<<
[ros2-8] 
[ros2-8] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[ros2-8] This error state is being overwritten:
[ros2-8] 
[ros2-8]   'Fast CDR exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:118'
[ros2-8] 
[ros2-8] with this new error message:
[ros2-8] 
[ros2-8]   ''Bad alloc' exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:123'
[ros2-8] 
[ros2-8] rcutils_reset_error() should be called after error handling to avoid this.
[ros2-8] <<<
[ros2-6] [WARN] [1753087100.521142222] [_ros2cli_86206]: Failed getting a result from calling /controller_manager/load_controller in 10.0. (Attempt 1 of 3.)
[ros2-7] Error loading controller, check controller_manager logs
[ERROR] [ros2-7]: process has died [pid 86208, exit code 1, cmd 'ros2 control load_controller --set-state active panda_arm_controller'].
[joint_state_publisher-2] 
[joint_state_publisher-2] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[joint_state_publisher-2] This error state is being overwritten:
[joint_state_publisher-2] 
[joint_state_publisher-2]   'Fast CDR exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:118'
[joint_state_publisher-2] 
[joint_state_publisher-2] with this new error message:
[joint_state_publisher-2] 
[joint_state_publisher-2]   ''Bad alloc' exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:123'
[joint_state_publisher-2] 
[joint_state_publisher-2] rcutils_reset_error() should be called after error handling to avoid this.
[joint_state_publisher-2] <<<
[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[spawn_entity.py-5] Traceback (most recent call last):
[spawn_entity.py-5]   File "/opt/ros/humble/lib/gazebo_ros/spawn_entity.py", line 372, in <module>
[spawn_entity.py-5]     main()
[spawn_entity.py-5]   File "/opt/ros/humble/lib/gazebo_ros/spawn_entity.py", line 367, in main
[spawn_entity.py-5]     exit_code = spawn_entity_node.run()
[spawn_entity.py-5]   File "/opt/ros/humble/lib/gazebo_ros/spawn_entity.py", line 228, in run
[spawn_entity.py-5]     success = self._spawn_entity(entity_xml, initial_pose, spawn_service_timeout)
[spawn_entity.py-5]   File "/opt/ros/humble/lib/gazebo_ros/spawn_entity.py", line 277, in _spawn_entity
[spawn_entity.py-5]     if client.wait_for_service(timeout_sec=timeout):
[spawn_entity.py-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/client.py", line 177, in wait_for_service
[spawn_entity.py-5]     time.sleep(sleep_time)
[spawn_entity.py-5] KeyboardInterrupt
[ros2-8] 
[ros2-8] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[ros2-8] This error state is being overwritten:
[ros2-8] 
[ros2-8]   ''Bad alloc' exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:123'
[ros2-8] 
[ros2-8] with this new error message:
[ros2-8] 
[ros2-8]   'Fast CDR exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:118'
[ros2-8] 
[ros2-8] rcutils_reset_error() should be called after error handling to avoid this.
[ros2-8] <<<
[gzserver-3] 
[gzserver-3] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[gzserver-3] This error state is being overwritten:
[gzserver-3] 
[gzserver-3]   ''Bad alloc' exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:123'
[gzserver-3] 
[gzserver-3] with this new error message:
[gzserver-3] 
[gzserver-3]   'Fast CDR exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:118'
[gzserver-3] 
[gzserver-3] rcutils_reset_error() should be called after error handling to avoid this.
[gzserver-3] <<<
[robot_state_publisher-1] [INFO] [1753087110.130365016] [rclcpp]: signal_handler(signum=2)
[robot_state_publisher-1] 
[robot_state_publisher-1] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[robot_state_publisher-1] This error state is being overwritten:
[robot_state_publisher-1] 
[robot_state_publisher-1]   'Fast CDR exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:118'
[robot_state_publisher-1] 
[robot_state_publisher-1] with this new error message:
[robot_state_publisher-1] 
[robot_state_publisher-1]   ''Bad alloc' exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:123'
[robot_state_publisher-1] 
[robot_state_publisher-1] rcutils_reset_error() should be called after error handling to avoid this.
[robot_state_publisher-1] <<<
[robot_state_publisher-1] 
[robot_state_publisher-1] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[robot_state_publisher-1] This error state is being overwritten:
[robot_state_publisher-1] 
[robot_state_publisher-1]   ''Bad alloc' exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:123'
[robot_state_publisher-1] 
[robot_state_publisher-1] with this new error message:
[robot_state_publisher-1] 
[robot_state_publisher-1]   'Fast CDR exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:118'
[robot_state_publisher-1] 
[robot_state_publisher-1] rcutils_reset_error() should be called after error handling to avoid this.
[robot_state_publisher-1] <<<
[ros2-6] 
[ros2-6] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[ros2-6] This error state is being overwritten:
[ros2-6] 
[ros2-6]   'Fast CDR exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:118'
[ros2-6] 
[ros2-6] with this new error message:
[ros2-6] 
[ros2-6]   ''Bad alloc' exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:123'
[ros2-6] 
[ros2-6] rcutils_reset_error() should be called after error handling to avoid this.
[ros2-6] <<<
[INFO] [robot_state_publisher-1]: process has finished cleanly [pid 86196]
[WARNING] [launch]: user interrupted with ctrl-c (SIGINT) again, ignoring...
[INFO] [gzserver-3]: process has finished cleanly [pid 86200]
[ERROR] [spawn_entity.py-5]: process has died [pid 86204, exit code -2, cmd '/opt/ros/humble/lib/gazebo_ros/spawn_entity.py -entity panda -topic robot_description --ros-args'].
[WARNING] [launch]: user interrupted with ctrl-c (SIGINT) again, ignoring...
[joint_state_publisher-2] 
[joint_state_publisher-2] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[joint_state_publisher-2] This error state is being overwritten:
[joint_state_publisher-2] 
[joint_state_publisher-2]   ''Bad alloc' exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:123'
[joint_state_publisher-2] 
[joint_state_publisher-2] with this new error message:
[joint_state_publisher-2] 
[joint_state_publisher-2]   'Fast CDR exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:118'
[joint_state_publisher-2] 
[joint_state_publisher-2] rcutils_reset_error() should be called after error handling to avoid this.
[joint_state_publisher-2] <<<
[WARNING] [launch]: user interrupted with ctrl-c (SIGINT) again, ignoring...
[ros2-6] 
[ros2-6] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[ros2-6] This error state is being overwritten:
[ros2-6] 
[ros2-6]   ''Bad alloc' exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:123'
[ros2-6] 
[ros2-6] with this new error message:
[ros2-6] 
[ros2-6]   'Fast CDR exception deserializing message of type rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_., at ./src/type_support_common.cpp:118'
[ros2-6] 
[ros2-6] rcutils_reset_error() should be called after error handling to avoid this.
[ros2-6] <<<
[joint_state_publisher-2] Traceback (most recent call last):
[joint_state_publisher-2]   File "/opt/ros/humble/lib/joint_state_publisher/joint_state_publisher", line 33, in <module>
[joint_state_publisher-2]     sys.exit(load_entry_point('joint-state-publisher==2.4.0', 'console_scripts', 'joint_state_publisher')())
[joint_state_publisher-2]   File "/opt/ros/humble/lib/python3.10/site-packages/joint_state_publisher/joint_state_publisher.py", line 470, in main
[joint_state_publisher-2]     jsp.destroy_node()
[joint_state_publisher-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/node.py", line 1686, in destroy_node
[joint_state_publisher-2]     self.destroy_publisher(self._publishers[0])
[joint_state_publisher-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/node.py", line 1566, in destroy_publisher
[joint_state_publisher-2]     publisher.destroy()
[joint_state_publisher-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 93, in destroy
[ERROR] [ros2-8]: process[ros2-8] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[ERROR] [ros2-6]: process[ros2-6] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[ERROR] [gzclient-4]: process[gzclient-4] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[ERROR] [joint_state_publisher-2]: process[joint_state_publisher-2] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [ros2-8]: sending signal 'SIGTERM' to process[ros2-8]
[joint_state_publisher-2]     self.__publisher.destroy_when_not_in_use()
[joint_state_publisher-2] KeyboardInterrupt
[INFO] [ros2-6]: sending signal 'SIGTERM' to process[ros2-6]
[INFO] [gzclient-4]: sending signal 'SIGTERM' to process[gzclient-4]
[INFO] [joint_state_publisher-2]: sending signal 'SIGTERM' to process[joint_state_publisher-2]
[ERROR] [gzclient-4]: process has died [pid 86202, exit code -15, cmd 'gzclient --gui-client-plugin=libgazebo_ros_eol_gui.so'].
[ERROR] [ros2-8]: process has died [pid 86211, exit code 2, cmd 'ros2 control load_controller --set-state active hand_controller'].
[ERROR] [joint_state_publisher-2]: process has died [pid 86198, exit code -2, cmd '/opt/ros/humble/lib/joint_state_publisher/joint_state_publisher --ros-args -r __node:=joint_state_publisher'].
[ERROR] [ros2-6]: process has died [pid 86206, exit code 2, cmd 'ros2 control load_controller --set-state active joint_state_broadcaster'].
